# Generated by Django 3.0 on 2019-12-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema', '0002_bookticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.CharField(max_length=60)),
                ('idMovie', models.CharField(max_length=60)),
                ('movieShow', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCustomer', models.CharField(max_length=60)),
                ('ticketPrice', models.FloatField()),
            ],
        ),
    ]
