# Generated by Django 3.0 on 2019-12-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema', '0003_cinematicket_customerticket_paymentticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCustomer', models.CharField(max_length=60)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.RenameModel(
            old_name='CinemaTicket',
            new_name='Cinema',
        ),
        migrations.RenameModel(
            old_name='CustomerTicket',
            new_name='Customer',
        ),
        migrations.DeleteModel(
            name='PaymentTicket',
        ),
    ]
