# Generated by Django 3.0 on 2020-01-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema', '0004_auto_20191216_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default='SOME STRING', max_length=60),
        ),
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.FloatField(default=130),
        ),
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.CharField(default='SOME STRING', max_length=60),
        ),
        migrations.AddField(
            model_name='movie',
            name='stars',
            field=models.CharField(default='SOME STRING', max_length=60),
        ),
        migrations.AddField(
            model_name='movie',
            name='types',
            field=models.CharField(default='SOME STRING', max_length=60),
        ),
    ]
